version: '3.3'

services:
  db:
    image: bitnami/mysql
    container_name: nestjs_start_db
    ports:
      - "3306:3306"
    volumes:
      - nestjs_start_dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    env_file:
      - .env

    # app:
    #   build: .
    #   container_name: nestjs_start_dbdata
    #   entrypoint: ./.docker/entrypoint.sh
    #   ports:
    #     - 3000:3000
    #   volumes:
    #     - .:/home/node/app

volumes:
  nestjs_start_dbdata:
    # external: true